### ISSUE TITLE
open files 

### ISSUE THREAD

**Issue by frontline-pcb** [alexbol99/debug-viewer1#16]
Hello Alex! 

We can't open files in the Debug Viewer as usual.
It worked today at morning, until I did refresh. Checked it from several different computers.

Thank you very much,
Dana

**Comment by alexbol99** [comment]
Hi, Dana,
Sorry, didn't noticed this issue.
Can you send me file that you cannot open, because it works for me.
Send me in email alexbol99@gmail.com or whatsapp
Thanks,
Alex
