### ISSUE TITLE
Hang-up while loading file with no shapes.

### ISSUE THREAD

**Issue by frontline-pcb** [alexbol99/debug-viewer1#20]
[odb_shape_172102.zip](https://github.com/alexbol99/debug-viewer1/files/9547886/odb_shape_172102.zip)

The program hands-up when loading file with no shapes:

<?xml version="1.0" encoding="UTF-8"?>
<shapes>
    <title>
        
    </title>
</shapes>

Please, make it to work like in the previous version:
* Show the file name in layers list.
* The file name should be dimmed or show in other way that there is a problematic file.

**Comment by alexbol99** [comment]
Bug fixed in v2.2.8
