### ISSUE TITLE
Incorrect shape draw

### ISSUE THREAD

**Issue by frontline-pcb** [alexbol99/debug-viewer1#21]
Hello,
Found problem in drawing a shape using Ctrl+V option.
See below shape data:
-		cont_op[nop].shape.s.cont,15	0x00000267d825be08 {{nedge=13 nalloc=13 is_isl=1} mat_cont_poly_struc, {pmin=13533816,12826540 pmax=13554234,12856278} mat_cont_lim_struc, ...}	mat_cont_struc[15]
+		[0]	{nedge=13 nalloc=13 is_isl=1} mat_cont_poly_struc	mat_cont_struc
+		[1]	{pmin=13533816,12826540 pmax=13554234,12856278} mat_cont_lim_struc	mat_cont_struc
+		[2]	{ps=13540940,12826803 pe=13539514,12826864 pc=13540258,12827556 cw=1} mat_curve_struc	mat_cont_struc
+		[3]	{ps=13539514,12826864 pe=13534708,12835196 pc=13554835,12841253 cw=1} mat_curve_struc	mat_cont_struc
+		[4]	{ps=13534708,12835196 pe=13534707,12835198} mat_seg_struc	mat_cont_struc
+		[5]	{ps=13534707,12835198 pe=13534683,12835274} mat_seg_struc	mat_cont_struc
+		[6]	{ps=13534683,12835274 pe=13534671,12835317} mat_seg_struc	mat_cont_struc
+		[7]	{ps=13534671,12835317 pe=13533816,12841248 pc=13554832,12841250 cw=1} mat_curve_struc	mat_cont_struc
+		[8]	{ps=13533816,12841248 pe=13533816,12844338} mat_seg_struc	mat_cont_struc
+		[9]	{ps=13533816,12844338 pe=13533824,12844463 pc=13534832,12844336 cw=1} mat_curve_struc	mat_cont_struc
+		[10]	{ps=13533824,12844463 pe=13549194,12856067 pc=13546852,12843187 cw=1} mat_curve_struc	mat_cont_struc
+		[11]	{ps=13549194,12856067 pe=13549320,12856036 pc=13549015,12855066 cw=1} mat_curve_struc	mat_cont_struc
+		[12]	{ps=13549320,12856036 pe=13553375,12855074 pc=13559872,12891486 cw=0} mat_curve_struc	mat_cont_struc
+		[13]	{ps=13553375,12855074 pe=13554231,12853994 pc=13553218,12854070 cw=1} mat_curve_struc	mat_cont_struc
+		[14]	{ps=13554231,12853994 pe=13540940,12826803 pc=13552523,12837985 cw=0} mat_curve_struc	mat_cont_struc

**Comment by alexbol99** [comment]
Bug fixed in new release 2.2.7
