### ISSUE TITLE
"Layer Properties / Name" edit box: crash when a string is copied to it from an external application

### ISSUE THREAD

**Issue by frontline-pcb** [alexbol99/debug-viewer1#27]
Open a layer in Debug Viewer, and press "Edit layer properties".
In "Layer properties" dialog, overwrite the content of "Name:" edit box with a word copied from an external text application (Notepad, Outlook, VS2019...), and press OK. Debug Viewer will crash.
Reproduces constantly, both in Chrome and Edge.
Arieh T.

**Comment by alexbol99** [comment]
Bug fixed in v2.2.8
