### ISSUE TITLE
Shape of type Square: a crash on attempt to load it to Debug Viewer

### ISSUE THREAD

**Issue by frontline-pcb** [alexbol99/debug-viewer1#28]
Copy-paste this one will cause crash:
+		square	{pc=31715659,54111965 r=71120}	mat_square_struc

Copy-paste a circle with the same data will display it as usual:
+		circle	{pc=31715659,54111965 r=71120}	mat_circle_struc

Arieh T.

**Comment by alexbol99** [comment]
Hi, Arie,
Indeed, square shape was not supported.
Added in v2.2.8
